#!/usr/bin/env bash
set -ue

# Origin one
#OUTPUT=1 ./run
#diff output.dat ../../results/backprop/output.dat

# For omp offloading
OUTPUT=1 ./run
cp output.dat /tmp/output.dat

OUTPUT=1 OMP_OFFLOAD=1 ./run
diff output.dat /tmp/output.dat
