#!/usr/bin/env bash
set -e

if [[ -z "${OFFLOAD}" ]]; then
# ./myocyte SPAN WORKLOAD MODE THREADS

# Parallel  inner work
#./myocyte 100 1 0 4

# parallel outter loop
#./myocyte 100 1 1 4
exit 1

else
# for omp offloading
./myocyte1d 100 5000 2 4
fi
