#!/usr/bin/env bash
set -ue

OUTPUT=1 ./run
for i in density momentum density_energy; do
    # TODO: a consistent error of 1.0e-5 looks like a bug
    numdiff -q -a 1.1e-5 $i ../../results/cfd/$i
done

